version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
      - ./.env
    # command:
    #   - --character-set-server=utf8mb4
    #   - --collation-server=utf8mb4_unicode_ci
    networks:
      - mynetwork
    ports:
      - 3306:3306

  webapp:
    container_name: web_app
    build: .
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && test -d static || mkdir static && python manage.py collectstatic --noinput && gunicorn 'giterview.wsgi:application' --bind=0.0.0.0:8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - rabbit
    networks:
      - mynetwork
    volumes:
      - ./:/usr/src/app

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - '15672'
    networks:
      - mynetwork

  celery_worker:
    container_name: celery_worker
    build: .
    command: sh -c "celery -A giterview worker -l info"
    ports: []
    depends_on:
      - mysql
      - rabbit
      - webapp
    networks:
      - mynetwork
    volumes:
      - ./celery_worker:/usr/src/app/celery_worker

  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   hostname: redis
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    driver: bridge
